image: python:2.7

before_script:
  - apt update
  - apt install -y python-pip python-pytest-cov # python-astropy python-photutils python-healpy
  - apt build-dep python-matplotlib python-numpy
  - pip install numpy astropy healpy photutils matplotlib
  
stages:
  - test

test_job:
  stage: test
  only:
    - master
  tags:
    - test
  script:
    - py.test