image: python:2.7

before_script:
  - apt update
  - apt install python-pip python-numpy python-pytest-cov python-astropy python-matplotlib
  - pip install healpy photutils 

stages:
  - test

test_job:
  stage: test
  only:
    - master
  tags:
    - test
  script:
    - py.test --cov
    