image: python:2.7

before_script:
  - apt update
  - apt install -y python-pip python-numpy python-pytest-cov python-matplotlib # python-astropy python-photutils python-healpy
  - pip install astropy healpy photutils --no-deps
  
stages:
  - test

test_job:
  stage: test
  only:
    - master
  tags:
    - test
  script:
    - py.test