sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
    global:
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='healpy photutils wcsaxes'
        - CONDA_DEPENDENCIES='astropy numpy matplotlib pytest-cov'

matrix:
    include:
          # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'
          
          
        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.5
          env: ASTROPY_VERSION=development

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
  - python setup.py $SETUP_CMD
