dist: trusty
sudo: required
language: python
python:
- 2.7
- 3.5
- 3.6
env:
  global:
  - NUMPY_VERSION=stable
  - ASTROPY_VERSION=stable
  - SETUP_CMD='test'
  - PIP_DEPENDENCIES='healpy photutils wcsaxes pytest-mpl'
  - CONDA_DEPENDENCIES='matplotlib pytest-cov'

addons:
  sonarqube:
      token:
          secure: bYpDSuIv7ZVKp8QLvnG9xIRmIiXbWh7WIOH01bg+T5pyZLLv4YTHrwLxejrkY9zj/eqXPvOLuiZIwmom/CKBtsmMwHiutNWqmga5bD5Uq2aaQVWY1Wafla46vvV+fI7XZk4zo35ErQoXIEi0s++uVNpy8PzDSz/CfvQXORJFx6rBdxRFlqWPtJCf4CgP2rslKUL8LHbLcjSYC7qAfayY6OsQqMVH+m8nWhkVv3la7vR3OsXgJca98gBvSoc4kFxxvlRkO6nb0aFmecnzzr8woVgMi6iZtGAuSteD2vTJQcFP32Bdh2wmWyKyRzqHGSxVaWcKN8hs7DAxeXdg5RMXels/nz09mcDO5jV0oCJXukefqiFAmHj2YzyxXAZg9S1IYBDGH1boaUUrfIVM/30HtNN1Zlv+bZMoNrusOkrLtAf93bqdKvSVL9JOYjUev8DdCMZ32qJKdXaZcyuCgrSRPLxd1AioHoLsY7Nco1rIBnQhBt/Ie4W7VaPPub53g4WkFK1KYETVV2IW0kl1QR6ZOs0Pw9KpulftXxj8f9+xKa5GDotNebM9t3Xcbz7l3SNEmgmHWQo3zmw0XyEEbTQw1nKld2XargY561jgZygt/Sj8vvxWQpDHE+rLl0XHX81ga7uQIfrI+9rHgOAEFRdqIpG/EzNIQpcIEXM9o8a1gWA=

matrix:
  include:
  - python: 2.7
    env: ASTROPY_VERSION=development
  - python: 3.6
    env: ASTROPY_VERSION=development
  - python: 2.7
    env: NUMPY_VERSION=1.10
install:
- git clone git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
script:
- MPLBACKEND="agg" python setup.py $SETUP_CMD
- sonar-scanner
