sudo: false

language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
    global:
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='healpy photutils wcsaxes'
        - CONDA_DEPENDENCIES='matplotlib pytest-cov pytest-mpl'

matrix:
    include:
        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development
        - python: 3.6
          env: ASTROPY_VERSION=development

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.10
          
        # - python: 2.7
        #   env: NUMPY_VERSION=1.9
        #        MATPLOTLIB_VERSION=1.4
        # - python: 2.7
        #   env: NUMPY_VERSION=1.8
        #        MATPLOTLIB_VERSION=1.3
        # - python: 2.7
        #   env: NUMPY_VERSION=1.7
        #        MATPLOTLIB_VERSION=1.2

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
  - python setup.py $SETUP_CMD
